-- Additional historical RFQs across KB classes (electronics, machining, stamping, injection, assembly, casting).
-- Applied automatically once when the database still has only the original 18 rfq_projects rows (see rfqDb.ts).

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (19, 1, '48V Platform', '48V Battery Management ECU', 'NB-KB-BMS-001', 'electronics', 'PCBA', 1.6, 100000, '2025-04-01', 0.05, 4, 'FCA Plant', 'Net 75', 2.5, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (19, 19, 'ElectroBuild Tier1', 127.5, 185000, 0.22, 4.2, 0.18, 'Submitted', 'Won', '2024-06-12 09:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (20, 1, 'Connected Vehicle', 'Gateway Telematics Module', 'NB-KB-GW-002', 'electronics', 'PCBA', 1.6, 85000, '2025-05-01', 0.05, 4, 'DDP Detroit', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (20, 20, 'ElectroBuild Tier1', 89.2, 120000, 0.18, 3.1, 0.21, 'Submitted', 'Quoted', '2024-07-01 11:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (21, 1, 'ADAS Suite', 'ADAS Sensor Fusion Hub PCB', 'NB-KB-ADAS-003', 'pcb_assembly', 'FR4', 1.6, 45000, '2025-06-01', 0.03, 5, 'FOB Munich', 'Net 90', 3.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (21, 21, 'SensorTech GmbH', 210.0, 320000, 0.35, 8.5, 0.4, 'Submitted', 'Won', '2024-05-20 08:30:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (22, 1, 'Smart Seat', 'Seat Memory ECU Module', 'NB-KB-SEECU-004', 'electronics', 'PCBA', 1.6, 220000, '2025-03-15', 0.05, 3, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (22, 22, 'ElectroBuild Tier1', 34.8, 48000, 0.09, 1.2, 0.07, 'Submitted', 'Won', '2024-08-10 14:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (23, 1, 'EV Powertrain', 'High Voltage DC-DC Converter Board', 'NB-KB-DCDC-005', 'electronics', 'PCBA', 2.0, 60000, '2025-07-01', 0.04, 4, 'FCA Plant', 'Net 75', 2.5, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (23, 23, 'PowerSemi Co', 156.0, 275000, 0.28, 5.4, 0.25, 'Submitted', 'Lost', '2024-09-02 10:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (24, 1, 'Connected Vehicle', 'T-Box Telematics ECU', 'NB-KB-TBOX-006', 'electronics', 'PCBA', 1.6, 95000, '2025-05-20', 0.05, 4, 'DDP Chicago', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (24, 24, 'ElectroBuild Tier1', 72.4, 98000, 0.15, 2.8, 0.19, 'Submitted', 'Won', '2024-06-28 09:15:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (25, 1, 'EV Powertrain', 'Traction Inverter Control PCB', 'NB-KB-INV-007', 'pcb_assembly', 'FR4', 2.4, 40000, '2025-08-01', 0.03, 5, 'FOB Shanghai', 'Net 90', 3.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (25, 25, 'PowerSemi Co', 312.0, 520000, 0.42, 12.0, 0.55, 'Submitted', 'Quoted', '2024-10-01 12:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (26, 1, '48V Platform', 'Battery Junction ECU', 'NB-KB-BJ-008', 'electronics', 'PCBA', 1.6, 78000, '2025-04-20', 0.05, 4, 'FCA Plant', 'Net 75', 2.5, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (26, 26, 'ElectroBuild Tier1', 98.0, 142000, 0.2, 3.5, 0.2, 'Submitted', 'Won', '2024-07-18 16:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (27, 1, 'Hydraulics Program', '6-Port Hydraulic Manifold Block', 'NB-KB-MAN-009', 'cnc_machining', 'AL6061', 18.0, 25000, '2025-02-01', 0.02, 4, 'FOB Detroit', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (27, 27, 'PrecisionFlow Inc', 42.5, 88000, 0.12, 0.9, 0.11, 'Submitted', 'Won', '2024-04-22 10:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (28, 1, 'Steering System', 'EPS Housing CNC Machined', 'NB-KB-ST-010', 'machining', 'AL7075', 22.5, 120000, '2025-03-01', 0.025, 4, 'DDP Munich', 'Net 75', 2.5, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (28, 28, 'PrecisionFlow Inc', 28.9, 125000, 0.1, 0.7, 0.14, 'Submitted', 'Won', '2024-05-05 09:30:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (29, 1, 'Brake Module', 'Valve Body Finish Machined', 'NB-KB-VLV-011', 'cnc_machining', 'Steel', 15.0, 90000, '2025-01-15', 0.02, 4, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (29, 29, 'MetalCraft SA', 19.4, 72000, 0.08, 0.55, 0.09, 'Submitted', 'Lost', '2024-03-11 11:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (30, 1, 'Thermal System', 'Coolant Pump Cover Billet', 'NB-KB-PMP-012', 'machining', 'AL6061', 14.0, 65000, '2025-04-10', 0.03, 3, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (30, 30, 'PrecisionFlow Inc', 15.2, 54000, 0.07, 0.45, 0.08, 'Submitted', 'Won', '2024-06-01 08:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (31, 1, 'Driveline', 'Precision Drive Shaft', 'NB-KB-SHAFT-013', 'cnc_machining', 'Steel', 25.0, 35000, '2025-05-01', 0.015, 4, 'DDP Detroit', 'Net 75', 2.5, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (31, 31, 'MetalCraft SA', 62.0, 95000, 0.14, 1.1, 0.2, 'Submitted', 'Quoted', '2024-07-12 13:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (32, 1, 'Brake Module', 'Caliper Body 5-Axis Machined', 'NB-KB-CAL-014', 'machining', 'AL7075', 30.0, 80000, '2025-02-20', 0.02, 4, 'FCA Plant', 'Net 75', 2.5, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (32, 32, 'PrecisionFlow Inc', 38.7, 110000, 0.11, 0.85, 0.12, 'Submitted', 'Won', '2024-04-30 15:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (33, 1, 'Wheel End', 'Wheel Bearing Housing Machined', 'NB-KB-BRG-015', 'cnc_machining', 'Steel', 20.0, 150000, '2025-06-01', 0.025, 3, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (33, 33, 'MetalCraft SA', 11.8, 42000, 0.06, 0.4, 0.07, 'Submitted', 'Won', '2024-08-20 09:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (34, 1, 'EV Crossover', 'Battery Tray Stamping Progressive', 'NB-KB-STP-016', 'stamping', 'HSLA', 2.0, 200000, '2025-01-01', 0.08, 3, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (34, 34, 'StampWorks LLC', 6.85, 72000, 0.11, 0.12, 0.05, 'Submitted', 'Won', '2024-05-15 10:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (35, 1, 'EV Utility', 'Heat Shield Stamped', 'NB-KB-STP-017', 'stamping', 'Aluminum', 0.8, 175000, '2025-02-01', 0.1, 3, 'FOB Shanghai', 'Net 75', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (35, 35, 'StampWorks LLC', 3.95, 28000, 0.06, 0.1, 0.04, 'Submitted', 'Quoted', '2024-06-10 11:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (36, 1, 'EV Premium', 'Seat Rail Stamping Transfer Die', 'NB-KB-STP-018', 'stamping', 'SPCC', 1.4, 165000, '2025-03-01', 0.08, 3, 'FOB Shanghai', 'Net 75', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (36, 36, 'StampWorks LLC', 5.2, 55000, 0.09, 0.12, 0.05, 'Submitted', 'Won', '2024-07-01 09:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (37, 1, 'EV Crossover', 'Motor Skid Mount Bracket Stamped', 'NB-KB-STP-019', 'stamping', 'SPHC', 2.2, 95000, '2025-04-01', 0.1, 3, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (37, 37, 'StampWorks LLC', 8.1, 48000, 0.1, 0.12, 0.06, 'Submitted', 'Lost', '2024-08-05 14:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (38, 1, 'Interior Trim', 'Instrument Panel Bezel A-Surface', 'NB-KB-INJ-020', 'injection_molding', 'PC/ABS', 2.8, 180000, '2025-05-01', 0.08, 4, 'DDP Detroit', 'Net 75', 2.5, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (38, 38, 'PlastiForm GmbH', 12.4, 420000, 0.15, 0.35, 0.12, 'Submitted', 'Won', '2024-05-22 10:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (39, 1, 'Interior Trim', 'Door Upper Trim Molded', 'NB-KB-INJ-021', 'injection_molding', 'PP', 2.2, 220000, '2025-05-15', 0.1, 3, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (39, 39, 'PlastiForm GmbH', 7.85, 280000, 0.1, 0.22, 0.09, 'Submitted', 'Won', '2024-06-18 08:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (40, 1, 'Underhood', 'Air Resonator Injection Molded', 'NB-KB-INJ-022', 'injection_molding', 'PA66', 3.5, 140000, '2025-06-01', 0.1, 3, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (40, 40, 'PlastiForm GmbH', 9.2, 195000, 0.11, 0.28, 0.1, 'Submitted', 'Quoted', '2024-07-25 12:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (41, 1, 'Connectors', 'High Voltage Connector Housing', 'NB-KB-INJ-023', 'injection_molding', 'PBT', 1.2, 500000, '2025-03-20', 0.05, 4, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (41, 41, 'PlastiForm GmbH', 0.85, 180000, 0.02, 0.05, 0.02, 'Submitted', 'Won', '2024-04-10 09:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (42, 1, 'Interior Trim', 'Seat Map Pocket Molded', 'NB-KB-INJ-024', 'injection_molding', 'ABS', 1.8, 300000, '2025-04-01', 0.1, 3, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (42, 42, 'PlastiForm GmbH', 2.15, 95000, 0.04, 0.08, 0.03, 'Submitted', 'Won', '2024-05-30 11:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (43, 1, 'Interior Trim', 'Console Side Trim Molded', 'NB-KB-INJ-025', 'injection_molding', 'PC/ABS', 2.0, 160000, '2025-07-01', 0.08, 4, 'DDP Detroit', 'Net 75', 2.5, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (43, 43, 'PlastiForm GmbH', 10.5, 310000, 0.12, 0.3, 0.11, 'Submitted', 'Lost', '2024-09-01 10:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (44, 1, 'Smart Seat', 'Seat Adjuster Assembly', 'NB-KB-ASM-026', 'assembly', 'Mixed', 0.0, 130000, '2025-02-15', 0.1, 4, 'FCA Plant', 'Net 75', 2.5, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (44, 44, 'AssemblePro NA', 142.0, 220000, 0.45, 2.1, 0.35, 'Submitted', 'Won', '2024-05-08 09:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (45, 1, 'Climate', 'HVAC Module Assembly', 'NB-KB-ASM-027', 'assembly', 'Mixed', 0.0, 85000, '2025-03-01', 0.1, 4, 'DDP Detroit', 'Net 75', 2.5, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (45, 45, 'AssemblePro NA', 198.5, 380000, 0.55, 3.2, 0.48, 'Submitted', 'Quoted', '2024-06-14 13:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (46, 1, 'Brake Module', 'Brake Pedal Subassembly', 'NB-KB-ASM-028', 'assembly', 'Mixed', 0.0, 200000, '2025-01-20', 0.08, 3, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (46, 46, 'AssemblePro NA', 24.6, 45000, 0.12, 0.4, 0.1, 'Submitted', 'Won', '2024-04-05 08:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (47, 1, 'Interior Trim', 'IP Subassembly Kitting', 'NB-KB-ASM-029', 'assembly', 'Mixed', 0.0, 95000, '2025-05-01', 0.1, 3, 'FCA Plant', 'Net 75', 2.5, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (47, 47, 'AssemblePro NA', 88.0, 120000, 0.28, 1.4, 0.22, 'Submitted', 'Won', '2024-07-20 10:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (48, 1, 'Thermal System', 'Thermal Valve Assembly Leak Tested', 'NB-KB-ASM-030', 'assembly', 'Mixed', 0.0, 70000, '2025-04-15', 0.05, 4, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (48, 48, 'AssemblePro NA', 31.2, 68000, 0.14, 0.55, 0.12, 'Submitted', 'Lost', '2024-08-12 15:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (49, 1, 'EV Powertrain', 'Motor End Cover Die Cast', 'NB-KB-CST-031', 'die_casting', 'A380', 8.0, 110000, '2025-03-10', 0.05, 4, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (49, 49, 'FoundryOne Ltd', 18.9, 520000, 0.12, 0.45, 0.11, 'Submitted', 'Won', '2024-05-25 09:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (50, 1, 'Chassis', 'Steering Knuckle Forging Finish', 'NB-KB-CST-032', 'forging', 'Steel', 35.0, 60000, '2025-02-01', 0.03, 4, 'DDP Detroit', 'Net 75', 2.5, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (50, 50, 'ForgeTech US', 54.0, 890000, 0.2, 1.2, 0.25, 'Submitted', 'Quoted', '2024-06-02 11:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (51, 1, 'Thermal System', 'Coolant Pump Housing Cast', 'NB-KB-CST-033', 'casting', 'AL-Si', 12.0, 88000, '2025-04-01', 0.04, 3, 'FOB Shanghai', 'Net 60', 2.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (51, 51, 'FoundryOne Ltd', 22.4, 410000, 0.13, 0.5, 0.13, 'Submitted', 'Won', '2024-07-08 10:00:00');

INSERT INTO rfq_projects (rfq_id, customer_id, program_name, part_name, part_number, process_family, material_grade, thickness_mm, annual_volume, sop_date, general_tolerance_mm, ppap_level, incoterm, payment_terms, annual_reduction_pct, rfq_case_code) VALUES (52, 1, 'Driveline', 'Differential Carrier Ductile Iron', 'NB-KB-CST-034', 'sand_casting', 'GJS-500', 40.0, 42000, '2025-06-01', 0.04, 4, 'FOB Munich', 'Net 90', 3.0, 'HIST');
INSERT INTO quote_submissions (submission_id, rfq_id, supplier_name, quoted_piece_price_usd, tooling_cost_usd, packaging_cost_per_pc, quality_cost_per_pc, freight_cost_per_pc, submission_status, award_result, submitted_at) VALUES (52, 52, 'FoundryOne Ltd', 186.0, 1200000, 0.65, 4.5, 0.6, 'Submitted', 'Lost', '2024-09-15 14:00:00');
